name    'illuminatis-racktables'
version '0.0.2'
source 'git@github.com:illuminatis/puppet-racktables.git'
author 'Leszek Charkiewicz'
license 'Apache License, Version 2.0'
summary 'Module to install RackTables asset management system.'
